---

- name: 'Install the MinIO operator'
  hosts: 'k3s1'
  gather_facts: true
  become: false
  module_defaults:
    kubernetes.core.helm:
      kubeconfig: './k3s-kubeconfig'
    kubernetes.core.k8s:
      kubeconfig: './k3s-kubeconfig'
    kubernetes.core.k8s_info:
      kubeconfig: './k3s-kubeconfig'

  tasks:

    - name: 'Create the minio-operator namespace'
      delegate_to: 'localhost'
      kubernetes.core.k8s:
        name: 'minio-operator'
        api_version: 'v1'
        kind: 'Namespace'
        state: 'present'

    - name: 'Install the MinIO operator via the helm chart'
      delegate_to: 'localhost'
      kubernetes.core.helm:
        chart_repo_url: 'https://operator.min.io'
        release_name: 'minio-operator'
        chart_ref: 'operator'
        release_namespace: 'minio-operator'
        release_values:
          operator:
            replicaCount: 1
