---

- name: 'Run playbook-install_k3s.yml'
  ansible.builtin.import_playbook: playbook-install_k3s.yml

- name: 'Run playbook-nginx_and_pvcs.yml'
  ansible.builtin.import_playbook: playbook-nginx_and_pvcs.yml

- name: 'Run playbook-minio_operator.yml'
  ansible.builtin.import_playbook: playbook-minio_operator.yml

- name: 'Run playbook-minio_tenant.yml'
  ansible.builtin.import_playbook: playbook-minio_tenant.yml
