---

- name: 'Run playbook-install_k3s.yml'
  ansible.builtin.import_playbook: playbook-install_k3s.yml

- name: 'Run playbook-nginx_and_pvcs.yml'
  ansible.builtin.import_playbook: playbook-nginx_and_pvcs.yml
